In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\spam.csv")
df.head(4)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...

In [21]:
df["Spam"] = df["Category"].apply(lambda x : 1 if x =="spam" else 0 )

In [22]:
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df["Message"], df["Spam"], test_size=0.33, random_state=42)

In [24]:
len(X_train)

3733

In [25]:
len(X_test)

1839

In [26]:
X_train.shape

(3733,)

In [27]:
cv = CountVectorizer()

In [28]:
X_train_cv = cv.fit_transform(X_train.values)
X_text_cv = cv.transform(X_test.values)

In [29]:
X_train_cv.shape

(3733, 7081)

In [30]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 49971 stored elements and shape (3733, 7081)>

In [31]:
cv.get_feature_names_out()[5008]

'protect'

In [32]:
cv.vocabulary_

{'yup': 7068,
 'not': 4414,
 'comin': 1735,
 'sent': 5511,
 'my': 4269,
 'scores': 5442,
 'to': 6329,
 'sophas': 5790,
 'and': 877,
 'had': 3007,
 'do': 2155,
 'secondary': 5467,
 'application': 934,
 'for': 2676,
 'few': 2565,
 'schools': 5436,
 'think': 6246,
 'if': 3279,
 'you': 7047,
 'are': 956,
 'thinking': 6249,
 'of': 4469,
 'applying': 937,
 'research': 5242,
 'on': 4512,
 'cost': 1834,
 'also': 848,
 'contact': 1796,
 'joke': 3500,
 'ogunrinde': 4488,
 'her': 3115,
 'school': 5435,
 'is': 3415,
 'one': 4517,
 'me': 4017,
 'the': 6218,
 'less': 3725,
 'expensive': 2471,
 'ones': 4518,
 'kothi': 3620,
 'print': 4958,
 'out': 4582,
 'marandratha': 3965,
 'its': 3435,
 'just': 3531,
 'effect': 2309,
 'irritation': 3413,
 'ignore': 3282,
 'it': 3427,
 'asked': 995,
 'call': 1453,
 'him': 3132,
 'now': 4425,
 'ok': 4493,
 'whatever': 6827,
 'juliana': 3523,
 'want': 6743,
 'hello': 3102,
 'got': 2925,
 'here': 3116,
 'st': 5880,
 'andrews': 880,
 'boy': 1330,
 'long': 3822,
 'way': 6775,
 'cold': 1710,
 'will': 6866,
 'keep': 3562,
 'posted': 4881,
 'no': 4381,
 'sir': 5663,
 'that': 6215,
 'why': 6851,
 'an': 874,
 'hr': 3216,
 'trip': 6428,
 'bus': 1418,
 'last': 3668,
 'week': 6798,
 'have': 3063,
 'another': 893,
 'audition': 1030,
 'next': 4355,
 'wednesday': 6795,
 'but': 1425,
 'might': 4085,
 'drive': 2227,
 'this': 6255,
 'time': 6301,
 'then': 6228,
 'ur': 6579,
 'physics': 4755,
 'get': 2844,
 'okie': 4498,
 'did': 2089,
 'see': 5478,
 'what': 6826,
 'your': 7052,
 'facebook': 2495,
 'sorry': 5794,
 'tomorrow': 6355,
 'senthil': 5513,
 'hsbc': 3219,
 'congrats': 1782,
 'nokia': 4390,
 '3650': 413,
 'video': 6657,
 'camera': 1471,
 'phone': 4744,
 '09066382422': 214,
 'calls': 1465,
 '150ppm': 282,
 'ave': 1048,
 '3mins': 430,
 'vary': 6628,
 'from': 2751,
 'mobiles': 4154,
 '16': 286,
 'close': 1675,
 '300603': 394,
 'post': 4877,
 'bcm4284': 1139,
 'ldn': 3693,
 'wc1n3xx': 6778,
 'wat': 6762,
 'finish': 2601,
 'lect': 3708,
 'today': 6335,
 'am': 853,
 'late': 3670,
 'be': 1146,
 'there': 6234,
 'at': 1014,
 'thing': 6244,
 'change': 1559,
 'sentence': 5512,
 'into': 3385,
 'because': 1156,
 'concentrate': 1766,
 'in': 3313,
 'educational': 2302,
 'career': 1501,
 'im': 3291,
 'leaving': 3707,
 'whenever': 6832,
 'we': 6779,
 'can': 1475,
 'still': 5925,
 'hook': 3179,
 'up': 6562,
 'too': 6368,
 'honeymoon': 3174,
 'outfit': 4585,
 'thought': 6266,
 'praps': 4913,
 'meant': 4025,
 'goodo': 2919,
 'll': 3793,
 'look': 3826,
 'dont': 2185,
 'pick': 4757,
 'when': 6831,
 'something': 5768,
 'important': 3304,
 'tell': 6160,
 'hrishi': 3217,
 'fuuuuck': 2783,
 'need': 4320,
 'stop': 5935,
 'sleepin': 5692,
 'sup': 6033,
 'well': 6812,
 'thats': 6217,
 'nice': 4359,
 'bad': 1081,
 'cant': 1486,
 'eat': 2285,
 'by': 1439,
 'make': 3939,
 'sure': 6047,
 'train': 6402,
 'worc': 6937,
 'foregate': 2679,
 'street': 5951,
 'shrub': 5622,
 'hill': 3130,
 'fun': 2769,
 'night': 4366,
 'honeybee': 3173,
 'said': 5380,
 'sweetest': 6071,
 'world': 6945,
 'god': 2893,
 'laughed': 3678,
 'amp': 868,
 'wait': 6722,
 'havnt': 3070,
 'met': 4074,
 'person': 4722,
 'reading': 5128,
 'msg': 4220,
 'moral': 4189,
 'even': 2415,
 'crack': 1864,
 'jokes': 3502,
 'gm': 2883,
 'gn': 2885,
 'ge': 2828,
 'hey': 3120,
 'babe': 1074,
 'far': 2523,
 'spun': 5872,
 'spk': 5849,
 'da': 1942,
 'mo': 4149,
 'dead': 1982,
 'wrld': 6970,
 'been': 1168,
 'sleeping': 5693,
 'sofa': 5751,
 'all': 832,
 'day': 1974,
 'cool': 1818,
 'nytho': 4450,
 'tx': 6477,
 'fonin': 2667,
 'hon': 3169,
 '2mwen': 375,
 'bk': 1246,
 'frmcloud': 2743,
 'storming': 5944,
 'wen': 6814,
 'lift': 3744,
 'phne': 4742,
 'say': 5422,
 'knw': 3611,
 'wt': 6975,
 'real': 5130,
 'meaning': 4021,
 'name': 4281,
 'girl': 2866,
 'yes': 7031,
 'who': 6843,
 'dat': 1967,
 'margaret': 3968,
 'she': 5565,
 'girlfrnd': 2867,
 'grahmbell': 2939,
 'invnted': 3396,
 'telphone': 6164,
 '4get': 475,
 'bt': 1389,
 'his': 3137,
 've': 6635,
 'fixed': 2618,
 'send': 5503,
 'test': 6185,
 'message': 4067,
 'how': 3210,
 'doing': 2174,
 'queen': 5058,
 'going': 2899,
 'royal': 5338,
 'wedding': 6794,
 'brother': 1374,
 'genius': 2835,
 'give': 2872,
 'sec': 5465,
 'about': 697,
 'clothes': 1680,
 'jewelry': 3487,
 'trips': 6430,
 'arm': 966,
 'feeling': 2553,
 'weak': 6780,
 'cuz': 1936,
 'shot': 5605,
 'so': 5748,
 'go': 2888,
 'please': 4805,
 'or': 4550,
 'tuesday': 6458,
 'evening': 2416,
 'won': 6924,
 'believe': 1187,
 'true': 6437,
 'incredible': 3328,
 'txts': 6485,
 'reply': 5232,
 'learn': 3702,
 'truly': 6440,
 'amazing': 855,
 'things': 6245,
 'blow': 1270,
 'mind': 4097,
 'o2fwd': 4454,
 'only': 4523,
 '18p': 294,
 'txt': 6478,
 'really': 5138,
 'lit': 3782,
 'hair': 3014,
 'fire': 2607,
 'room': 5326,
 'number': 4436,
 'again': 786,
 'wanna': 6742,
 'knocking': 3606,
 'right': 5295,
 'door': 2191,
 'shuhui': 5626,
 'suntec': 6032,
 'steamboat': 5915,
 'noe': 4385,
 'where': 6835,
 'sexy': 5538,
 'buns': 1410,
 'told': 6344,
 'adore': 758,
 'loverboy': 3860,
 'hope': 3183,
 'remember': 5208,
 'thank': 6206,
 'sister': 5665,
 'law': 3685,
 'those': 6262,
 'meatballs': 4029,
 'grins': 2965,
 'love': 3854,
 'waiting': 6725,
 'car': 1493,
 'bored': 1303,
 'cos': 1832,
 'outside': 4589,
 'nothing': 4417,
 'home': 3167,
 'stuff': 5972,
 'watch': 6763,
 'tv': 6468,
 'hours': 3206,
 'before': 1174,
 'went': 6816,
 'cut': 1932,
 'calling': 1463,
 'everyone': 2427,
 'saying': 5425,
 'cancer': 1482,
 'throat': 6275,
 'hurts': 3245,
 'talk': 6111,
 'answering': 899,
 'everyones': 2428,
 'more': 4190,
 'babysitting': 1078,
 'monday': 4176,
 'forced': 2678,
 'myself': 4273,
 'slice': 5699,
 'hungry': 3238,
 'tho': 6261,
 'sucks': 6003,
 'mark': 3971,
 'getting': 2852,
 'worried': 6947,
 'he': 3072,
 'knows': 3610,
 'sick': 5633,
 'turn': 6464,
 'down': 2204,
 'pizza': 4782,
 'lol': 3815,
 'face': 2494,
 'lt': 3876,
 'gt': 2981,
 'select': 5489,
 'any': 906,
 'astrology': 1011,
 'quick': 5064,
 'workin': 6941,
 'overtime': 4600,
 'nigpun': 4369,
 'prakesh': 4912,
 'know': 3607,
 'dunno': 2260,
 'means': 4024,
 'teju': 6155,
 'great': 2955,
 'run': 5359,
 'ttyl': 6456,
 'jus': 3530,
 'thanks': 6207,
 'gift': 2859,
 'available': 1044,
 'though': 6265,
 'kiss': 3597,
 'miss': 4120,
 'baby': 1077,
 '4eva': 473,
 'until': 6560,
 'lets': 3730,
 'pilates': 4770,
 'meanwhile': 4026,
 'project': 4989,
 'twins': 6474,
 'hi': 3123,
 'match': 3988,
 'honey': 3172,
 'sweetheart': 6072,
 'darling': 1963,
 'sugar': 6010,
 'plum': 4813,
 'boytoy': 1335,
 'smacks': 5713,
 'ass': 1003,
 'gym': 3003,
 'lions': 3771,
 'england': 2361,
 'tone': 6357,
 'lionm': 3769,
 'mono': 4180,
 'lionp': 3770,
 'poly': 4847,
 'www': 6983,
 'ringtones': 5304,
 'co': 1695,
 'uk': 6502,
 'original': 4568,
 'best': 1200,
 'tones': 6358,
 '3gbp': 425,
 'network': 4338,
 'operator': 4538,
 'rates': 5104,
 'apply': 935,
 'new': 4346,
 'handset': 3030,
 '750': 566,
 'anytime': 917,
 'mins': 4106,
 'half': 3018,
 'price': 4952,
 'line': 3761,
 'rental': 5223,
 'camcorder': 1469,
 '08000930705': 48,
 'delivery': 2032,
 'okay': 4494,
 'sleep': 5691,
 'later': 3673,
 'barred': 1112,
 'stores': 5942,
 'life': 3740,
 'twat': 6469,
 'orange': 4554,
 'dungerees': 2259,
 'came': 1470,
 'wanted': 6745,
 'decking': 2003,
 'first': 2612,
 'punch': 5031,
 'come': 1731,
 'sch': 5433,
 'neva': 4341,
 '1st': 307,
 'lor': 3834,
 'otherwise': 4577,
 'part': 4653,
 'job': 3493,
 'na': 4277,
 'tuition': 6459,
 'gonna': 2908,
 'death': 1991,
 'leave': 3705,
 'note': 4415,
 'says': 5426,
 'robs': 5315,
 'fault': 2536,
 'avenge': 1049,
 'ard': 955,
 '530': 507,
 'haha': 3010,
 'they': 6241,
 'most': 4196,
 'tmr': 6323,
 'forfeit': 2683,
 'pls': 4812,
 'full': 2766,
 'fees': 2556,
 'university': 6543,
 'florida': 2642,
 'seem': 5482,
 'actually': 742,
 'holla': 3163,
 'back': 1079,
 'was': 6755,
 'checking': 1589,
 'happening': 3043,
 'around': 972,
 'area': 957,
 'yeah': 7020,
 'depressed': 2050,
 'sittin': 5671,
 'waitin': 6724,
 'ring': 5299,
 'wind': 6871,
 'drops': 2235,
 'scary': 5430,
 'ryan': 5367,
 'our': 4581,
 'some': 5760,
 'point': 4838,
 'iron': 3409,
 'plan': 4788,
 'weekend': 6799,
 'reach': 5120,
 'office': 4480,
 'decimal': 1999,
 'mobile': 4153,
 'problem': 4972,
 'cann': 1483,
 'voice': 6688,
 'asa': 986,
 'free': 2718,
 'alright': 846,
 'advice': 769,
 'enjoy': 2363,
 'ma': 3909,
 'try': 6445,
 'aaooooright': 688,
 'work': 6940,
 'wake': 6726,
 'morning': 4194,
 'itself': 3436,
 'however': 3211,
 'suggest': 6012,
 'stays': 5911,
 'with': 6895,
 'someone': 5764,
 'able': 695,
 'ors': 4570,
 'every': 2422,
 'stool': 5934,
 'called': 1457,
 'choose': 1632,
 'future': 2782,
 'probably': 4971,
 'swing': 6077,
 'wee': 6796,
 'bit': 1239,
 'ever': 2421,
 'figure': 2580,
 'years': 7022,
 'hahaha': 3011,
 'use': 6597,
 'brain': 1336,
 'dear': 1987,
 'meeting': 4038,
 'tel': 6156,
 'shall': 5552,
 'finished': 2603,
 'yet': 7034,
 'urgent': 6583,
 '09061213237': 178,
 'landline': 3651,
 '5000': 492,
 'cash': 1516,
 'luxury': 3894,
 'canary': 1478,
 'islands': 3421,
 'holiday': 3162,
 'await': 1055,
 'collection': 1718,
 'cs': 1901,
 'sae': 5375,
 'po': 4821,
 'box': 1318,
 '177': 290,
 'm227xy': 3902,
 'wot': 6954,
 'bitch': 1240,
 'fucking': 2761,
 'chickened': 1608,
 'messaged': 4068,
 'would': 6956,
 'woould': 6935,
 'buzz': 1434,
 'didn': 2091,
 'hear': 3081,
 'word': 6938,
 'lovely': 3857,
 'xxx': 7000,
 'were': 6817,
 'together': 6338,
 'should': 5607,
 'thinkin': 6248,
 'text': 6190,
 'read': 5126,
 'light': 3746,
 'guess': 2989,
 'easy': 2284,
 'enough': 2368,
 'congratulations': 1783,
 'good': 2910,
 'friend': 2737,
 '000': 1,
 'xmas': 6993,
 'prize': 4966,
 'claim': 1649,
 '08718726978': 137,
 '10p': 241,
 'per': 4707,
 'minute': 4109,
 'national': 4299,
 'rate': 5103,
 'weather': 6786,
 'over': 4595,
 'words': 6939,
 'may': 4009,
 'dismay': 2139,
 'many': 3962,
 'times': 6302,
 'olol': 4507,
 'printed': 4959,
 'forum': 2698,
 'guy': 2999,
 'exact': 2447,
 'same': 5395,
 'prob': 4970,
 'which': 6838,
 'gpu': 2934,
 'replacement': 5230,
 'hopefully': 3185,
 'very': 6647,
 'hurting': 3244,
 'meaningful': 4022,
 'lines': 3764,
 'compromised': 1760,
 'everything': 2431,
 'end': 2349,
 'gud': 2986,
 'mornin': 4193,
 'idk': 3277,
 're': 5119,
 'since': 5655,
 'moved': 4208,
 'butting': 1428,
 'heads': 3077,
 'freedom': 2720,
 'vs': 6700,
 'responsibility': 5260,
 'tired': 6307,
 'much': 4238,
 'other': 4575,
 'shit': 5584,
 'deal': 1983,
 'barely': 1109,
 'keeping': 3563,
 'once': 4515,
 'gets': 2848,
 'added': 747,
 'watching': 6766,
 'ride': 5294,
 'equally': 2383,
 'uneventful': 6531,
 'pesky': 4730,
 'cyclists': 1939,
 'model': 4164,
 'sony': 5782,
 'ericson': 2386,
 'der': 2053,
 'luks': 3887,
 'forgot': 2689,
 'modl': 4165,
 'naughty': 4304,
 'pix': 4780,
 'pic': 4756,
 'like': 3750,
 'flash': 2625,
 'madam': 3919,
 'take': 6104,
 'care': 1498,
 'oh': 4489,
 'ar': 951,
 'dis': 2127,
 'yijue': 7039,
 'happy': 3047,
 'wif': 6857,
 'gek1510': 2832,
 'realy': 5140,
 'don': 2181,
 'recognise': 5162,
 'confused': 1780,
 'credits': 1883,
 'topped': 6378,
 'http': 3221,
 'bubbletext': 1392,
 'com': 1725,
 'renewal': 5220,
 'pin': 4773,
 'tgxxrz': 6201,
 'decision': 2000,
 'anything': 915,
 'ready': 5129,
 'meet': 4036,
 'created': 1878,
 'gap': 2805,
 'between': 1208,
 'fingers': 2600,
 'made': 3920,
 'comes': 1733,
 'fills': 2587,
 'gaps': 2806,
 'holding': 3161,
 'hand': 3026,
 'already': 845,
 'loving': 3864,
 'entry': 2375,
 'weekly': 6801,
 'comp': 1743,
 'chance': 1557,
 'win': 6869,
 'ipod': 3404,
 'pod': 4836,
 '80182': 589,
 'std': 5912,
 '08452810073': 67,
 'details': 2068,
 '18': 291,
 'min': 4094,
 'wun': 6982,
 'signing': 5644,
 'hee': 3093,
 'textpod': 6199,
 '40gb': 445,
 '250': 341,
 'wk': 6905,
 '84128': 616,
 'ts': 6448,
 'net': 4334,
 'custcare': 1927,
 '08712405020': 105,
 'kallis': 3544,
 'wont': 6931,
 'play': 4796,
 'two': 6476,
 'odi': 4468,
 'working': 6942,
 'tried': 6427,
 'adding': 750,
 'zeros': 7074,
 'savings': 5420,
 'bloody': 1269,
 'hell': 3100,
 'surname': 6053,
 'mr': 4216,
 'ill': 3287,
 'clue': 1687,
 'spanish': 5817,
 'begins': 1180,
 'thanx': 6212,
 'lot': 3842,
 'help': 3105,
 'accidant': 715,
 'tookplace': 6370,
 'somewhere': 5773,
 'ghodbandar': 2855,
 'rd': 5117,
 'traffic': 6401,
 'moves': 4209,
 'slovely': 5706,
 'plz': 4818,
 'slip': 5702,
 'worry': 6949,
 'hdd': 3071,
 'casing': 1520,
 'training': 6403,
 'shrek': 5620,
 '3d': 423,
 'natalja': 4298,
 '25': 340,
 'inviting': 3395,
 '440': 454,
 'sms': 5731,
 'ac': 708,
 'nat27081980': 4295,
 'frnd': 2744,
 '62468': 530,
 'as': 985,
 'request': 5238,
 'melle': 4047,
 'oru': 4572,
 'minnaminunginte': 4104,
 'nurungu': 4439,
 'vettam': 6648,
 'has': 3056,
 'set': 5525,
 'callertune': 1460,
 'callers': 1459,
 'press': 4942,
 'copy': 1825,
 'friends': 2738,
 'diddy': 2090,
 'neighbor': 4327,
 'toothpaste': 6374,
 'green': 2959,
 'quote': 5072,
 'jerry': 3481,
 'cartoon': 1514,
 'irritates': 3412,
 'always': 851,
 'loves': 3862,
 'vry': 6699,
 'fails': 2503,
 'express': 2483,
 'nyt': 4449,
 'beerage': 1171,
 'except': 2452,
 'saturday': 5414,
 'sunday': 6025,
 '100': 232,
 'music': 4257,
 'vouchers': 6697,
 'starting': 5901,
 'draw': 2214,
 '87066': 632,
 'tscs': 6450,
 'idew': 3275,
 'skillgame': 5679,
 '1winaweek': 313,
 'age16': 790,
 '150ppermesssubscription': 281,
 'ummmmmaah': 6509,
 'returns': 5278,
 'sweet': 6070,
 'heart': 3084,
 'birthday': 1237,
 'strict': 5955,
 'than': 6203,
 'teacher': 6142,
 'bcoz': 1140,
 'teaches': 6143,
 'lesson': 3727,
 'conducts': 1773,
 'exam': 2449,
 'lessons': 3728,
 'guessin': 2991,
 'ain': 806,
 'decided': 1997,
 'people': 4705,
 'vote': 6693,
 'caring': 1505,
 'losers': 3837,
 'fancy': 2518,
 'drink': 2223,
 'completely': 1756,
 'form': 2692,
 'clark': 1654,
 'utter': 6608,
 'waste': 6759,
 'tirupur': 6310,
 'started': 5900,
 'truro': 6441,
 'hospital': 3196,
 'ext': 2486,
 'side': 5635,
 'pretty': 4946,
 'channel': 1562,
 'msgs': 4226,
 'iam': 3256,
 'addicted': 748,
 'msging': 4222,
 'wrong': 6972,
 'bslvyl': 1385,
 'dependents': 2046,
 'us': 6593,
 'id': 3268,
 'proof': 4998,
 'rs': 5342,
 'allow': 838,
 'within': 6898,
 'days': 1975,
 'ringtone': 5302,
 'tms': 6325,
 'widelive': 6856,
 'index': 3332,
 'wml': 6914,
 '1b6a5ecef91ff9': 299,
 '37819': 418,
 'true18': 6438,
 '0430': 15,
 'jul': 3521,
 '05': 16,
 'ask': 993,
 'sat': 5409,
 'them': 6225,
 'ditto': 2147,
 'anymore': 909,
 'peace': 4693,
 'neighbors': 4328,
 'didnt': 2092,
 'happened': 3041,
 'while': 6839,
 'adventuring': 768,
 'strike': 5956,
 'red': 5170,
 'bird': 1232,
 'antelope': 902,
 'begin': 1179,
 'toplay': 6377,
 'fieldof': 2573,
 'selfindependence': 5493,
 'flower': 2644,
 'contention': 1802,
 'grow': 2974,
 'random': 5095,
 'supports': 6041,
 'srt': 5878,
 'thnk': 6259,
 'ps3': 5016,
 'through': 6276,
 'usb': 6595,
 'slowly': 5710,
 'clean': 1661,
 'blood': 1268,
 'ten': 6169,
 'special': 5825,
 'miracle': 4112,
 'jess': 3483,
 'eve': 2413,
 'reality': 5134,
 'fantasy': 2522,
 'show': 5613,
 '08707509020': 85,
 '20p': 326,
 'ntt': 4431,
 'ltd': 3877,
 '1327': 266,
 'croydon': 1893,
 'cr9': 1862,
 '5wb': 519,
 '0870': 69,
 'lose': 3836,
 'kg': 3575,
 'mon': 4175,
 'after': 781,
 'hip': 3135,
 'hop': 3182,
 'orchard': 4557,
 'weigh': 6803,
 'alrite': 847,
 'jod': 3495,
 'hows': 3212,
 'revision': 5284,
 'goin': 2897,
 'keris': 3570,
 'bin': 1230,
 'doin': 2172,
 'smidgin': 5721,
 'cum': 1914,
 'college': 1720,
 'xx': 6997,
 'freezing': 2725,
 'mom': 4171,
 'missing': 4124,
 'happen': 3039,
 'talking': 6114,
 'alian': 829,
 'roger': 5320,
 'gent': 2836,
 'trying': 6447,
 'weekends': 6800,
 'shows': 5618,
 '1000': 233,
 'guaranteed': 2984,
 '09064012160': 195,
 'code': 1704,
 'k52': 3535,
 'valid': 6619,
 '12hrs': 262,
 'liked': 3751,
 'erutupalam': 2394,
 'thandiyachu': 6204,
 'jason': 3466,
 'place': 4784,
 'hour': 3205,
 '11': 244,
 'months': 4186,
 'entitled': 2374,
 'update': 6567,
 'latest': 3674,
 'colour': 1722,
 '08002986030': 52,
 'elaborating': 2326,
 'safety': 5378,
 'aspects': 1002,
 'issues': 3425,
 'bishan': 1238,
 'lar': 3664,
 'nearer': 4311,
 'buy': 1429,
 ...}

In [33]:
X_train_arr = X_train_cv.toarray()

In [34]:
X_train_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
mm = MultinomialNB()

In [37]:
mm.fit(X_train_cv,y_train)

MultinomialNB()

In [38]:
y_pred = mm.predict(X_text_cv)

In [39]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1593
           1       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839

# test model

In [44]:
msg = {"Exact IT Solutions Pvt. Ltd. and 19 more companies are hiring Software Engineer"}

In [45]:
result = cv.transform(msg)
mm.predict(result)

array([0])

In [57]:
nw = {"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"}

In [58]:
result = cv.transform(nw)
mm.predict(result)

array([1])